
import { GoogleGenAI, GenerateContentResponse } from "@google/genai";

// IMPORTANT: The API key MUST be available as process.env.API_KEY.
// For client-side Vite applications, this requires specific configuration
// in vite.config.js (or .ts) to define 'process.env.API_KEY'.
// Example vite.config.ts:
// define: { 'process.env.API_KEY': JSON.stringify(process.env.VITE_API_KEY) }
// And then VITE_API_KEY should be in your .env file.
const apiKey = process.env.API_KEY;

if (!apiKey) {
  // This error will be thrown if process.env.API_KEY is not defined at runtime.
  // It's crucial for the user to ensure their environment (e.g., Vite config)
  // makes this variable available to the client-side code.
  throw new Error("API_KEY is not defined. Please set it in your environment variables and ensure it's accessible to the client-side application.");
}

const ai = new GoogleGenAI({ apiKey });

const TEXT_MODEL_NAME = "gemini-2.5-flash-preview-04-17";
const IMAGE_MODEL_NAME = "imagen-3.0-generate-002";

export async function generateStory(prompt: string): Promise<string> {
  try {
    console.log(`Generating story with prompt: "${prompt}" using model ${TEXT_MODEL_NAME}`);
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: TEXT_MODEL_NAME,
      contents: prompt,
      config: {
        temperature: 0.7,
        topK: 32,
        topP: 0.9,
        // For creative story generation, default thinking budget is fine (omitting thinkingConfig)
      }
    });
    
    const text = response.text;
    if (!text) {
      throw new Error('No text generated by the API.');
    }
    console.log("Story generated successfully.");
    return text;
  } catch (error) {
    console.error(`Gemini API error in generateStory:`, error);
    if (error instanceof Error) {
        throw new Error(`Failed to generate story using Gemini API: ${error.message}`);
    }
    throw new Error('An unknown error occurred while generating story with Gemini API.');
  }
}

export async function generateImage(prompt: string): Promise<string> {
  try {
    console.log(`Generating image with prompt: "${prompt}" using model ${IMAGE_MODEL_NAME}`);
    const response = await ai.models.generateImages({
        model: IMAGE_MODEL_NAME,
        prompt: prompt,
        config: { numberOfImages: 1, outputMimeType: 'image/png' }, // Use image/png for broader compatibility
    });

    if (!response.generatedImages || response.generatedImages.length === 0) {
      throw new Error('No image generated by the API.');
    }
    
    const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
    if (!base64ImageBytes) {
        throw new Error('Generated image data is empty.');
    }
    console.log("Image generated successfully.");
    return `data:image/png;base64,${base64ImageBytes}`;
  } catch (error) {
    console.error(`Gemini API error in generateImage:`, error);
     if (error instanceof Error) {
        // Preserve the original error message, which is helpful for issues like billing.
        throw new Error(`Failed to generate image using Gemini API: ${error.message}`);
    }
    throw new Error('An unknown error occurred while generating image with Gemini API.');
  }
}
    